/*
1. Assume that a bank offers two types of accounts: standard and premium, from which a
customer can select one while opening a bank account. An account holder can deposit any
amount ofmoney into his or her account, but when withdrawing, a premium account holder can
withdraw up to Rs 10 lakh in a day, whilst a regular account holder can withdraw up to Rs I lakh
free of charge and up to Rs 5 lakh with a .05% penalty. In this regard write ajava program with
the following specifi cations:
i. Create a super class Account that contains various information of a accomt holder like
account number, account type, name, current balance etc. along with day, month and year
of last deposit. Account class also contains three methods: one for checking current
balance, one for depositing money and the third for withdrawing money. New account is
created with the personal information in the constructor of the class and the account
number is generated by auto-increment.
*/

import java.util.Scanner;

class Account {
    static int nextAccountNo = 1000;

    String name;
    String type;
    int account_no;
    float balance;

    // Constructor
    Account(String name, String type, float balance) {
        this.name = name;
        this.type = type;
        this.balance = balance;
        this.account_no = ++nextAccountNo;
    }

    void deposit(float amount) {
        if (amount > 0) {
            balance += amount;
            System.out.println("Deposit successful.");
        } else {
            System.out.println("Invalid deposit amount.");
        }
    }

    void checkBalance() {
        System.out.println("Current Balance: Rs " + balance);
    }

    void withdraw(float amount) {
        // overridden in subclasses
    }
}

class Standard extends Account {

    Standard(String name, float balance) {
        super(name, "Standard", balance);
    }

    @Override
    void withdraw(float amount) {
        if (amount <= 100000 && amount <= balance) {
            balance -= amount;
            System.out.println("Withdrawal successful.");
        }
        else if (amount > 100000 && amount <= 500000 && amount <= balance) {
            float penalty = amount * 0.0005f;
            balance -= (amount + penalty);
            System.out.println("Withdrawal successful with penalty.");
        }
        else {
            System.out.println("Withdrawal limit exceeded or insufficient balance.");
        }
    }
}

class Premium extends Account {

    Premium(String name, float balance) {
        super(name, "Premium", balance);
    }

    @Override
    void withdraw(float amount) {
        if (amount <= 1000000 && amount <= balance) {
            balance -= amount;
            System.out.println("Withdrawal successful.");
        } else {
            System.out.println("Withdrawal limit exceeded or insufficient balance.");
        }
    }
}

public class Main {
    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        Account acc;

        System.out.println("Select the type of account:");
        System.out.println("1) Standard Account");
        System.out.println("2) Premium Account");
        System.out.print("Enter your choice: ");
        int choice = sc.nextInt();
        sc.nextLine();

        System.out.print("Enter name: ");
        String name = sc.nextLine();

        System.out.print("Enter initial balance: ");
        float balance = sc.nextFloat();

        if (choice == 1) {
            acc = new Standard(name, balance);
        } else {
            acc = new Premium(name, balance);
        }

        System.out.print("Enter withdrawal amount: ");
        float amount = sc.nextFloat();

        acc.withdraw(amount);
        acc.checkBalance();

        sc.close();
    }
}
